/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAppPoolService,
  IAppPoolServiceInterface,
} from "../IAppPoolService";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "referralCode",
        type: "uint256",
      },
    ],
    name: "addLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "removeLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAppPoolService__factory {
  static readonly abi = _abi;
  static createInterface(): IAppPoolServiceInterface {
    return new utils.Interface(_abi) as IAppPoolServiceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAppPoolService {
    return new Contract(address, _abi, signerOrProvider) as IAppPoolService;
  }
}
